// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-_x40VSI42tVTUFo0vJ0s-3JQz5C24Uc',
    appId: '1:774562815060:web:a48cb8c9a340e04feca1c1',
    messagingSenderId: '774562815060',
    projectId: 'my-prayer-alarm',
    authDomain: 'my-prayer-alarm.firebaseapp.com',
    storageBucket: 'my-prayer-alarm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQzIbbHqE9xWk7-OK9FZ1e2mbB-GTGTI',
    appId: '1:774562815060:android:79c5d3fce476732eeca1c1',
    messagingSenderId: '774562815060',
    projectId: 'my-prayer-alarm',
    storageBucket: 'my-prayer-alarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgaYlBYsooxCB8G47kTvalwUZbOpGV0Fg',
    appId: '1:774562815060:ios:ab5e2f649f468917eca1c1',
    messagingSenderId: '774562815060',
    projectId: 'my-prayer-alarm',
    storageBucket: 'my-prayer-alarm.appspot.com',
    iosClientId: '774562815060-rblt6sjo44joha3e36226dq3h9s138s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayerAlarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgaYlBYsooxCB8G47kTvalwUZbOpGV0Fg',
    appId: '1:774562815060:ios:ab5e2f649f468917eca1c1',
    messagingSenderId: '774562815060',
    projectId: 'my-prayer-alarm',
    storageBucket: 'my-prayer-alarm.appspot.com',
    iosClientId: '774562815060-rblt6sjo44joha3e36226dq3h9s138s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayerAlarm',
  );
}
